use std::{
    collections::HashMap,
    io::{Read, Write},
    path::{Path, PathBuf},
    sync::atomic::{AtomicBool, Ordering},
    time::{Duration, Instant},
};

use anyhow::Context;
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use probe_rs::{
    Core, MemoryInterface, Permissions,
    architecture::arm::dp::DpAddress,
    flashing::{
        self, DownloadOptions, ElfLoader, ElfOptions, FlashProgress, ProgressEvent,
        ProgressOperation,
    },
    probe::{DebugProbeSelector, Probe, WireProtocol, list::Lister},
};
use tracing_subscriber::EnvFilter;
use x7dap::{Bitstream, X7, auto_tap_idx, fixup_zynq_ir_lengths};
use z7_ps7init::{PsInitOps, RegOp, RegOpKind};

/// Default chunk size for RAM writes during `commit()`, in bytes. Without chunking, each RAM
/// region is written to the target in one single call and progress jumps straight from 0% to
/// 100% - see [`ProgressBars`]. Overridable via `--ram-chunk-size`.
const DEFAULT_RAM_CHUNK_SIZE: u64 = 64 * 1024;

/// Config file name looked up in the current directory when `--config` isn't given.
const DEFAULT_CONFIG_FILE_NAME: &str = "z7_run.toml";

/// Progress-bar template shared by every bar `z7-run` shows for an operation with a known total
/// length (bitstream flash, RAM writes with a known size). Adopted from probe-rs's own CLI
/// (`probe-rs-tools/src/bin/probe-rs/util/flash.rs`'s `active()`), so output looks consistent
/// with `probe-rs`'s own flashing progress.
const PROGRESS_TEMPLATE_KNOWN_LENGTH: &str = "{msg:>13.green.bold} {spinner} {percent:>3}% [{bar:20}] {bytes:>10} @ {bytes_per_sec:>12} (ETA {eta})";

/// Builds the [`ProgressStyle`] shared by every bar `z7-run` shows, from an indicatif template
/// string. Panics if `template` is invalid - only ever called with static templates.
fn progress_bar_style(template: &str) -> ProgressStyle {
    ProgressStyle::with_template(template)
        .expect("static progress bar template is valid")
        .progress_chars("##-")
}

/// Default JTAG speed for the bitstream flash step specifically, in kHz, when
/// `--jtag-speed-khz`/the config isn't set. Every other step in this tool falls back to the
/// probe's own default speed instead, but that default is very conservative and flashing a
/// multi-MB bitstream at it is painfully slow - matches openFPGALoader's own default.
const DEFAULT_FLASH_JTAG_SPEED_KHZ: u32 = 6_000;

/// Parses a `u64` from either decimal or `0x`/`0X`-prefixed hex, for CLI args like `--check-ddr`
/// where the natural way to write the value is as a hex address.
fn parse_maybe_hex_u64(s: &str) -> Result<u64, std::num::ParseIntError> {
    match s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        Some(hex) => u64::from_str_radix(hex, 16),
        None => s.parse(),
    }
}

/// Resolves a path that came from a config file: if it's relative, resolves it relative to the
/// config file's own directory rather than the current working directory, so a config file
/// referencing files next to it keeps working no matter where `z7-run` is invoked from.
fn resolve_relative_to_config(config_path: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        config_path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(path)
    }
}

/// Z7 flasher application.
///
/// Unifies all the steps required to flash and run a Rust program on a Z7-based system,
/// including flashing a PL design. It uses the probe-rs library to talk to the debug probe.
///
/// - Connects to the probe.
/// - Resets the target.
/// - Executes the PS7 (PLL/clock/DDR) init sequence.
/// - Optionally flashes a bitstream to the programmable logic, via x7dap's native probe-rs
///   JTAG access.
/// - Flashes and runs the given ELF file.
#[derive(clap::Parser, Debug)]
#[command(version, about, verbatim_doc_comment)]
struct Cli {
    /// Path to the PS7 PLL/clock/DDR/DDRIOB register op sequences: either an AMD `ps7_init.tcl`
    /// script directly (a `.tcl` extension, parsed the same way `z7-ps7init-extract` does), or a
    /// RON file as generated by `z7-ps7init-extract` (any other extension). Overrides the
    /// `ZYNQ_REGS` env var when set.
    #[arg(long)]
    regs: Option<PathBuf>,

    /// Path to the ELF file to flash and run.
    elf: PathBuf,

    /// Check the DDR after init by writing/reading a few distinct bit patterns at the given test
    /// address (decimal or `0x`-prefixed hex, e.g. `0x00100000`).
    #[arg(long, value_parser = parse_maybe_hex_u64)]
    check_ddr: Option<u64>,

    /// Path to a config TOML file (bitstream path, serial console). If not given, looks for
    /// `z7_run.toml` in the current directory; if that isn't found either, the bitstream step
    /// falls back to the `ZYNQ_BITSTREAM` env var and the serial console step is skipped
    /// entirely.
    #[arg(long)]
    config: Option<PathBuf>,

    /// Debug probe to use, as `VID:PID[-INTERFACE][:SERIAL]` (same format as probe-rs itself,
    /// e.g. `0403:6010` or `0403:6010:ABCD1234`). If not given and multiple probes are
    /// connected, you'll be prompted to pick one interactively.
    #[arg(long)]
    probe: Option<DebugProbeSelector>,

    /// Chunk size, in bytes, for writing the ELF into RAM. Smaller chunks give more granular
    /// progress reporting at the cost of a bit of overhead. Defaults to
    /// [`DEFAULT_RAM_CHUNK_SIZE`]; passing this explicitly as the same value as the ELF size (or
    /// larger) writes each RAM region in one go, same as probe-rs's own `--ram-chunk-size` when
    /// left unset, so progress then jumps straight to 100%.
    #[arg(long)]
    ram_chunk_size: Option<u64>,

    /// Don't show a progress bar while flashing.
    #[arg(long)]
    no_progress: bool,

    /// JTAG clock speed in kHz. Overrides the config file's `jtag_speed_khz` when given. If
    /// neither is set, the probe's own default speed is used.
    #[arg(long)]
    jtag_speed_khz: Option<u32>,

    /// Read the ELF back off the target after flashing and compare it against what was written.
    /// Off by default, since verification takes roughly as long as the write itself.
    #[arg(long)]
    verify: bool,
}

/// Config for things that don't belong on the command line, split by what they actually
/// describe: `fpga` is genuinely board-specific (the bitstream to load), but `serial` mostly
/// isn't - which serial port shows up depends on what's plugged into *this* machine, not on the
/// board - it just lives in the same file for convenience.
#[derive(Debug, Default, serde::Deserialize)]
struct Config {
    #[serde(default)]
    fpga: FpgaConfig,
    /// Serial console to attach to (printing anything received to stdout) once every init/flash
    /// step is done and the target is running.
    #[serde(default)]
    serial: Option<SerialConfig>,
    /// JTAG clock speed in kHz. Overridden by `--jtag-speed-khz` when given; if neither is set,
    /// the probe's own default speed is used.
    #[serde(default)]
    jtag_speed_khz: Option<u32>,
}

#[derive(Debug, Default, serde::Deserialize)]
struct FpgaConfig {
    /// Path to the bitstream to load before the ELF is flashed. Overridden by the
    /// `ZYNQ_BITSTREAM` env var when set, so a quick one-off override doesn't require editing the
    /// config file. Relative paths are resolved relative to the config file's own directory, not
    /// the current working directory, so the config stays self-contained wherever `z7-run` is
    /// invoked from.
    #[serde(default)]
    bitstream: Option<PathBuf>,
}

#[derive(Debug, serde::Deserialize)]
struct SerialConfig {
    /// Serial port device path (e.g. `/dev/ttyUSB1`).
    port: String,
    /// Baud rate. Defaults to 115200, the near-universal default for these boards' UARTs.
    #[serde(default = "default_baud_rate")]
    baud_rate: u32,
}

#[inline]
const fn default_baud_rate() -> u32 {
    115_200
}

/// Picks which debug probe to open. With `selector` given, matches against it directly (same as
/// probe-rs's own `--probe`) and errors if that doesn't resolve to exactly one probe. Without a
/// selector: opens the only probe if there's just one, or prompts interactively to choose among
/// several - there's no correct default to silently pick when more than one probe is connected.
///
/// Also returns a concrete [`DebugProbeSelector`] identifying exactly the probe that was opened,
/// so a later re-open (releasing and re-acquiring the same USB interface, e.g. to switch between
/// raw JTAG access and an ARM debug session) can pass it back in and skip the interactive prompt
/// the second time around.
fn select_probe(
    lister: &Lister,
    selector: Option<&DebugProbeSelector>,
) -> anyhow::Result<(Probe, DebugProbeSelector)> {
    let probes = lister.list(selector);
    let info = match probes.len() {
        0 => match selector {
            Some(selector) => anyhow::bail!("no debug probe found matching --probe {selector}"),
            None => anyhow::bail!("no debug probes found"),
        },
        1 => &probes[0],
        _ => {
            if let Some(selector) = selector {
                anyhow::bail!(
                    "multiple debug probes match --probe {selector}; narrow it down further \
                     (e.g. add the interface or serial number)"
                );
            }
            println!("Multiple debug probes found:");
            for (i, probe) in probes.iter().enumerate() {
                println!("  [{i}] {probe}");
            }
            print!("Select a probe [0-{}]: ", probes.len() - 1);
            std::io::stdout().flush()?;
            let mut input = String::new();
            std::io::stdin()
                .read_line(&mut input)
                .with_context(|| "failed to read probe selection")?;
            let index: usize = input
                .trim()
                .parse()
                .with_context(|| format!("invalid probe selection: {:?}", input.trim()))?;
            probes
                .get(index)
                .ok_or_else(|| anyhow::anyhow!("selection {index} is out of range"))?
        }
    };
    let selector = DebugProbeSelector::from(info);
    Ok((info.open()?, selector))
}

/// Opens a probe via [`select_probe`] and switches it to JTAG protocol. This is a fresh `Probe`
/// handle every time, which is what's needed whenever switching between raw JTAG access and an
/// ARM debug session on the same probe - a `Session` consumes the `Probe` it's attached from with
/// no way to get it back out, so getting back to raw JTAG means releasing and re-opening it.
fn open_probe_as_jtag(
    selector: Option<&DebugProbeSelector>,
) -> anyhow::Result<(Probe, DebugProbeSelector)> {
    let lister = Lister::new();
    let (mut probe, probe_selector) = select_probe(&lister, selector)?;
    probe.select_protocol(WireProtocol::Jtag)?;
    Ok((probe, probe_selector))
}

/// Renders [`ProgressEvent`]s emitted by [`flashing::FlashLoader::commit`] as live terminal
/// progress bars. probe-rs itself only ships this event stream (see `FlashProgress`) - the
/// library deliberately stays UI-agnostic since consumers render it differently (the probe-rs
/// CLI's own indicatif bars, the VS Code debug adapter, ...) - so there's no ready-made bar
/// widget to reuse here. z7-run only ever flashes into RAM (no on-chip flash algorithm is
/// involved), so in practice there's just one bar ("Writing RAM"); this stays generic over
/// [`ProgressOperation`] regardless, in case a target/ELF combination ever exercises the flash
/// erase/program/verify path too.
struct FlashProgressBars {
    multi_progress: MultiProgress,
    bars: HashMap<&'static str, ProgressBar>,
}

impl FlashProgressBars {
    fn new() -> Self {
        Self {
            multi_progress: MultiProgress::new(),
            bars: HashMap::new(),
        }
    }

    fn operation_label(operation: ProgressOperation) -> &'static str {
        match operation {
            ProgressOperation::Fill => "Reading flash",
            ProgressOperation::Erase => "Erasing",
            ProgressOperation::Program => "Programming",
            ProgressOperation::Verify => "Verifying",
            ProgressOperation::Ram => "Writing RAM",
        }
    }

    fn bar_mut(&mut self, operation: ProgressOperation) -> &mut ProgressBar {
        self.bars
            .entry(Self::operation_label(operation))
            .or_insert_with(ProgressBar::hidden)
    }

    fn handle(&mut self, event: ProgressEvent) {
        match event {
            ProgressEvent::FlashLayoutReady { .. } | ProgressEvent::Started(_) => {}
            ProgressEvent::AddProgressBar { operation, total } => {
                let bar = self.multi_progress.add(match total {
                    // A length is promised, but only known for sure once flashing starts; start
                    // at 1 so the bar doesn't render as already at 100%.
                    Some(total) => ProgressBar::new(total.max(1)),
                    None => ProgressBar::no_length(),
                });
                let template = if bar.length().is_some() {
                    PROGRESS_TEMPLATE_KNOWN_LENGTH
                } else {
                    "{msg:>13.green.bold} {spinner} {elapsed}"
                };
                bar.set_style(progress_bar_style(template));
                bar.set_message(Self::operation_label(operation));
                bar.enable_steady_tick(Duration::from_millis(100));
                self.bars.insert(Self::operation_label(operation), bar);
            }
            ProgressEvent::Progress {
                operation, size, ..
            } => self.bar_mut(operation).inc(size),
            ProgressEvent::Failed(operation) => self.bar_mut(operation).abandon(),
            ProgressEvent::Finished(operation) => {
                let bar = self.bar_mut(operation);
                bar.set_length(bar.position());
                bar.finish();
            }
            ProgressEvent::DiagnosticMessage { message } => {
                let _ = self.multi_progress.println(message);
            }
        }
    }
}

/// Flashes the given bitstream via x7dap's native probe-rs JTAG access.
///
/// Must be called with no probe-rs `Session` alive on `probe`: a raw JTAG access and an ARM
/// debug session can't be held open on the same probe at once.
///
/// Shows progress in the same style as [`FlashProgressBars`] (rather than x7dap's own bar, so it
/// looks consistent with the rest of `z7-run`'s output) unless `no_progress`.
fn flash_bitstream(probe: &mut Probe, data: &[u8], no_progress: bool) -> anyhow::Result<()> {
    let bar = if no_progress {
        ProgressBar::hidden()
    } else {
        let bar = ProgressBar::new(data.len().max(1) as u64);
        bar.set_style(progress_bar_style(PROGRESS_TEMPLATE_KNOWN_LENGTH));
        bar.set_message("Writing FPGA");
        bar.enable_steady_tick(Duration::from_millis(100));
        bar
    };

    probe.attach_to_unspecified()?;
    let jtag = probe
        .try_as_jtag_probe()
        .with_context(|| "selected probe does not support JTAG")?;

    let chain = jtag.scan_chain()?.to_vec();

    // auto_tap_idx only looks at each TAP's IDCODE, never at its IR length, so it works
    // correctly even before the IR length fixup below.
    let (tap_idx, idcode) =
        auto_tap_idx(&chain).with_context(|| "no 7-series IDCODE found in JTAG chain")?;

    // Zynq-7000's two-TAP PL/PS chain is a shape the generic IR length detection can get
    // backward without reporting an error - see fixup_zynq_ir_lengths. Only apply it once a
    // Zynq-7000 is actually confirmed present, per its documented precondition.
    if idcode.is_zynq7000()
        && let Some(fixed) = fixup_zynq_ir_lengths(&chain)
    {
        jtag.set_scan_chain(&fixed)?;
    }

    jtag.select_target(tap_idx)?;

    let mut x7 = X7::new(jtag, idcode);
    x7.program_with_callback(data, |n| bar.set_position(n as u64))?;
    bar.finish();
    Ok(())
}

/// Set by the `Ctrl+C` handler. The background reader thread spawned by [`open_serial_console`]
/// polls this and exits cleanly instead of running forever, which lets the serial port close
/// normally (via `Drop`) instead of the whole process just being killed mid-read. Everything
/// before that phase (probe selection, flashing, register ops) doesn't watch this flag, since
/// nothing there holds a resource that benefits from orderly teardown; a second `Ctrl+C` forces
/// an immediate exit regardless, in case the first one arrived too early to matter.
static SHUTDOWN_REQUESTED: AtomicBool = AtomicBool::new(false);

/// Opens the configured serial port and immediately starts reading from it on a background
/// thread, forwarding every chunk received to the returned channel. Must be called before either
/// core is released: the target can start UARTing out its own boot log the instant
/// `core.run()`/`core1.run()` return, and those probe-rs calls are themselves slow JTAG
/// round-trips, so opening (and reading) the port only afterward reliably loses the target's
/// first output.
///
/// Nothing is printed here. Capturing into a channel instead of straight to stdout means the
/// bytes that arrive during that gap get printed in order, before anything live, once
/// [`run_serial_console`] starts draining it - not interleaved with the flashing progress bars
/// or tracing output still on screen at that point, so the overall sequence stays clean.
/// Receiving end of the channel [`open_serial_console`] forwards bytes into, plus the handle of
/// the background thread reading them - what [`run_serial_console`] then drains.
type SerialReader = (
    std::sync::mpsc::Receiver<Vec<u8>>,
    std::thread::JoinHandle<()>,
);

fn open_serial_console(serial: &SerialConfig) -> anyhow::Result<SerialReader> {
    tracing::info!(
        "attaching to serial console: {} @ {} baud",
        serial.port,
        serial.baud_rate
    );
    let port = serialport::new(&serial.port, serial.baud_rate)
        .timeout(Duration::from_millis(100))
        .open()
        .with_context(|| format!("failed to open serial port {}", serial.port))?;

    let (tx, rx) = std::sync::mpsc::channel();
    let handle = std::thread::spawn(move || serial_reader_loop(port, tx));
    Ok((rx, handle))
}

/// Reads from `port` and forwards every chunk received to `tx`, until either `tx`'s receiver is
/// gone, a real read error occurs, or [`SHUTDOWN_REQUESTED`] is set. This is the body of the
/// background thread [`open_serial_console`] spawns; `port` and `tx` are passed in explicitly
/// (rather than captured by the spawned closure) so it's clear at the call site exactly what
/// data crosses into the thread.
fn serial_reader_loop(
    mut port: Box<dyn serialport::SerialPort>,
    tx: std::sync::mpsc::Sender<Vec<u8>>,
) {
    let mut buf = [0u8; 1024];
    loop {
        if SHUTDOWN_REQUESTED.load(Ordering::Relaxed) {
            return;
        }
        match port.read(&mut buf) {
            Ok(0) => {}
            Ok(n) => {
                if tx.send(buf[..n].to_vec()).is_err() {
                    // Receiver gone, i.e. the main thread exited; nothing left to do.
                    return;
                }
            }
            Err(e)
                if e.kind() == std::io::ErrorKind::TimedOut
                    || e.kind() == std::io::ErrorKind::WouldBlock => {}
            // Can't propagate this to `main`'s `Result` from a background thread; log it and
            // stop, which closes the channel and ends `run_serial_console`'s read loop.
            Err(e) => {
                tracing::error!("serial console read error: {e}");
                return;
            }
        }
    }
}

/// Prints everything received on `rx` to stdout, forever, in the order it arrived (including
/// whatever was already buffered before this was called). Meant to be the last thing `main` does:
/// once the target is up and running, this is how you watch its UART output without needing a
/// separate terminal/tool.
///
/// `rx` only closes once the reader thread's closure returns and drops its `Sender`, so by the
/// time this loop ends the thread is already finished or about to be; `handle.join()` below just
/// confirms that and surfaces a panic there instead of silently treating it as a clean
/// disconnect.
fn run_serial_console((rx, handle): SerialReader) -> anyhow::Result<()> {
    let mut stdout = std::io::stdout();
    for chunk in rx {
        stdout.write_all(&chunk)?;
        stdout.flush()?;
    }
    if handle.join().is_err() {
        anyhow::bail!("serial console reader thread panicked");
    }
    Ok(())
}

/// Writes a few distinct bit patterns to DDR and reads them back, to give an unambiguous
/// pass/fail signal for whether DDR is actually working, independent of whether an app flashed
/// afterward appears to run. A stuck-at fault or bit swap from bad calibration won't show up as
/// a probe-rs error during flashing (writing bytes and issuing `core.run()` can't detect a CPU
/// that immediately crashes on a garbage stack pointer), so this needs to be checked directly.
fn ddr_sanity_check(core: &mut Core, base_addr: u64) -> anyhow::Result<()> {
    let patterns: [u32; 4] = [0xDEAD_BEEF, 0x0000_0000, 0xFFFF_FFFF, 0xAAAA_5555];
    for (i, &pattern) in patterns.iter().enumerate() {
        core.write_word_32(base_addr + (i as u64) * 4, pattern)?;
    }
    for (i, &pattern) in patterns.iter().enumerate() {
        let addr = base_addr + (i as u64) * 4;
        let read_back = core.read_word_32(addr)?;
        if read_back != pattern {
            anyhow::bail!(
                "DDR sanity check failed at {addr:#010x}: wrote {pattern:#010x}, read back {read_back:#010x}"
            );
        }
    }
    Ok(())
}

/// Executes a sequence of register ops (as extracted from `ps7_init.tcl`) directly over the
/// core's memory interface (i.e. via JTAG), in order.
fn execute_register_ops(core: &mut Core, ops: &[RegOp]) -> anyhow::Result<()> {
    for op in ops {
        tracing::debug!(
            "performing register op: {} {:#010x}",
            op.name.as_deref().unwrap_or("<unnamed>"),
            op.addr()
        );
        match op.kind {
            RegOpKind::Write { addr, val } => core.write_word_32(addr as u64, val)?,
            RegOpKind::MaskWrite { addr, mask, val } => {
                let addr = addr as u64;
                let current = core.read_word_32(addr)?;
                core.write_word_32(addr, (current & !mask) | (val & mask))?;
            }
            RegOpKind::MaskPoll { addr, mask } => {
                let deadline = std::time::Instant::now() + Duration::from_secs(1);
                loop {
                    let current = core.read_word_32(addr as u64)?;
                    if current & mask != 0 {
                        break;
                    }
                    if std::time::Instant::now() > deadline {
                        anyhow::bail!(
                            "timed out waiting for register {addr:#010x} & {mask:#010x} != 0 (last read: {current:#010x})"
                        );
                    }
                }
            }
        }
    }
    Ok(())
}

fn main() -> anyhow::Result<()> {
    use clap::Parser as _;

    // Default to info for this app but warn-and-above for probe-rs, which is otherwise very
    // chatty at info level (JTAG scans, AP/DP setup, session teardown, ...). RUST_LOG still
    // overrides this entirely when set.
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("info,probe_rs=warn")),
        )
        .init();

    // First `Ctrl+C` asks the serial console's background reader thread to shut down cleanly
    // (see `SHUTDOWN_REQUESTED`/`open_serial_console`). Nothing outside that phase watches the
    // flag, so if it arrives earlier (still flashing, prompting for a probe, ...) it does
    // nothing by itself; a second `Ctrl+C` always exits immediately, so that case still
    // terminates the process instead of becoming uninterruptible.
    ctrlc::set_handler(|| {
        if SHUTDOWN_REQUESTED.swap(true, Ordering::SeqCst) {
            std::process::exit(130);
        }
    })
    .context("failed to install Ctrl+C handler")?;

    let cli = Cli::parse();

    // An explicit --config must exist (fail loud); an implicit default lookup is fine to come up
    // empty (just proceed without a config).
    let config_path: Option<PathBuf> = match &cli.config {
        Some(path) => Some(path.clone()),
        None => {
            let default_path = PathBuf::from(DEFAULT_CONFIG_FILE_NAME);
            default_path.exists().then_some(default_path)
        }
    };

    let config: Config = match &config_path {
        Some(path) => {
            tracing::info!("loading config from: {}", path.display());
            let config_str = std::fs::read_to_string(path)
                .with_context(|| format!("failed to read config file {}", path.display()))?;
            toml::from_str(&config_str)
                .with_context(|| format!("failed to parse config file {}", path.display()))?
        }
        None => {
            tracing::debug!(
                "no --config given and no {DEFAULT_CONFIG_FILE_NAME} in the current directory, \
                 proceeding without one"
            );
            Config::default()
        }
    };

    // `--regs` and `ZYNQ_REGS` are both plain CLI/env-relative paths, resolved relative to the
    // current working directory like any other CLI argument - no config-file involved, so no
    // `resolve_relative_to_config` needed here.
    let regs: PathBuf = cli
        .regs
        .clone()
        .or_else(|| std::env::var_os("ZYNQ_REGS").map(PathBuf::from))
        .ok_or_else(|| {
            anyhow::anyhow!(
                "no PS7 init ops file specified: pass --regs <path> (.tcl or .ron) or set \
                 ZYNQ_REGS"
            )
        })?;

    // A quick `ZYNQ_BITSTREAM=... z7-run ...` shouldn't require editing the config file.
    let bitstream = std::env::var("ZYNQ_BITSTREAM").ok().or_else(|| {
        let bitstream = config.fpga.bitstream.as_ref()?;
        let resolved = match &config_path {
            Some(config_path) => resolve_relative_to_config(config_path, bitstream),
            None => bitstream.clone(),
        };
        Some(resolved.display().to_string())
    });

    tracing::info!("loading PS7 init ops from: {}", regs.display());
    let regs_str = std::fs::read_to_string(&regs)
        .with_context(|| format!("failed to read PS7 init ops file {}", regs.display()))?;
    let is_tcl = regs
        .extension()
        .is_some_and(|ext| ext.eq_ignore_ascii_case("tcl"));
    let ps7_init_ops: PsInitOps = if is_tcl {
        z7_ps7init::parse_ps7_init_tcl(&regs_str)
    } else {
        ron::from_str(&regs_str)
            .with_context(|| format!("failed to parse PS7 init ops file {}", regs.display()))?
    };

    let jtag_speed_khz = cli.jtag_speed_khz.or(config.jtag_speed_khz);

    // `probe_selector` identifies exactly this probe, so re-opening it later (to switch
    // between raw JTAG access and an ARM debug session) doesn't need to re-prompt.
    let (mut probe, probe_selector) = open_probe_as_jtag(cli.probe.as_ref())?;
    if let Some(jtag_speed_khz) = jtag_speed_khz {
        tracing::info!("setting JTAG speed to {jtag_speed_khz} kHz");
        probe.set_speed(jtag_speed_khz)?;
    }

    tracing::info!("attaching to target board");

    let mut session = probe.attach("X7Z", Permissions::default())?;
    let mut core = session.core(0)?;

    tracing::info!("resetting and halting core");
    core.reset_and_halt(Duration::from_millis(100))?;

    // Execution order mirrors the real ps7_init.tcl call order: DDRIOB config -> PLL init ->
    // clock init -> DDR init -> post-config. DDRIOB configures the
    // physical I/O buffers (drive strength/termination) for the DDR pins, so it has to be done
    // before the DDR controller starts its calibration handshake, or that handshake never
    // completes (status register stuck at 0, DDR_INIT_OPS mask_poll times out). Post-config
    // (level shifters + PL reset deassert) runs last, same as on real hardware where
    // `ps7_post_config` is called right after `ps7_init` regardless of whether/when a bitstream
    // gets loaded - the PL powers up in reset and stays there until this runs.
    tracing::info!("performing board clock and DDR init");
    execute_register_ops(&mut core, &ps7_init_ops.ddriob_init_ops)
        .with_context(|| "DDRIOB register setup")?;
    tracing::debug!("bringing up PLLs");
    execute_register_ops(&mut core, &ps7_init_ops.pll_init_ops)
        .with_context(|| "PLL register setup")?;
    tracing::debug!("configuring clocks");
    execute_register_ops(&mut core, &ps7_init_ops.clock_init_ops)
        .with_context(|| "Clock config setup")?;
    tracing::debug!("initializing DDR controller");
    execute_register_ops(&mut core, &ps7_init_ops.ddr_init_ops)
        .with_context(|| "DDR controller register setup")?;
    tracing::debug!("running PS7 post-config (level shifters, PL reset deassert)");
    execute_register_ops(&mut core, &ps7_init_ops.post_config_ops)
        .with_context(|| "PS7 post-config register setup")?;

    if let Some(test_addr) = cli.check_ddr {
        tracing::info!("running DDR sanity check at {test_addr:#010x}");
        ddr_sanity_check(&mut core, test_addr).with_context(|| "DDR sanity check")?;
        tracing::info!("DDR sanity check passed");
    }

    drop(core);

    // Flashing the bitstream via x7dap needs raw JTAG access, but `Session` doesn't expose a way
    // to get that back out of an already-attached probe - `Probe::attach()` consumes the `Probe`
    // into `Session`'s private `interfaces` field, and there's no `into_probe()` or equivalent to
    // reverse it. So this isn't a USB/hardware necessity, it's a probe-rs API limitation: we drop
    // the session, open a fresh `Probe` (via the cached `probe_selector`, so it doesn't re-prompt)
    // to do the raw JTAG flash, then re-attach a new session afterward. Reprogramming the PL
    // (FPGA fabric) doesn't touch the PS's DDR/PLL/SLCR state, so the init done above survives the
    // round trip - only the JTAG connection itself needs to be redone. Skip the whole dance when
    // there's nothing to flash, to avoid the extra latency/reset churn.
    //
    // TODO(robin): look into adding a `Session::into_probe()` (or equivalent) upstream in
    // probe-rs, so this can go back to a single open/attach with no reopen at all.
    if let Some(bitstream) = &bitstream {
        tracing::info!("Flashing FPGA design: {bitstream}");
        let data = Bitstream::from_path(bitstream)
            .with_context(|| format!("failed to load bitstream {bitstream}"))?;

        // `probe` was already consumed by `probe.attach()` above; dropping `session` alone
        // releases the underlying USB JTAG handle.
        drop(session);

        let (mut probe, _) = open_probe_as_jtag(Some(&probe_selector))?;
        probe.set_speed(jtag_speed_khz.unwrap_or(DEFAULT_FLASH_JTAG_SPEED_KHZ))?;
        flash_bitstream(&mut probe, data.data(), cli.no_progress)?;

        // Shadowing `probe` below does not drop this one early - it would otherwise stay
        // open (holding the USB interface) until the end of this block, causing the
        // re-open just below to fail with "interface is busy".
        drop(probe);

        tracing::info!("re-attaching probe after bitstream flash");
        let (mut probe, _) = open_probe_as_jtag(Some(&probe_selector))?;
        if let Some(jtag_speed_khz) = jtag_speed_khz {
            probe.set_speed(jtag_speed_khz)?;
        }
        session = probe.attach("X7Z", Permissions::default())?;
    }

    let arm_if = session.get_arm_interface()?;
    arm_if.select_debug_port(DpAddress::Default)?;

    let format = ElfLoader(ElfOptions::default());

    // Must outlive `download_opts`: its `progress` field borrows this closure-captured state, and
    // is used up to (and dropped as part of) `loader.commit()` below.
    let mut progress_bars = (!cli.no_progress).then(FlashProgressBars::new);

    let mut download_opts = DownloadOptions::default();
    download_opts.verify = cli.verify;
    // Without chunking, each RAM region is written to the target in one single call and progress
    // jumps straight from 0% to 100%.
    download_opts.ram_chunk_size = Some(cli.ram_chunk_size.unwrap_or(DEFAULT_RAM_CHUNK_SIZE));
    download_opts.progress = FlashProgress::new(|event| {
        if let Some(progress_bars) = &mut progress_bars {
            progress_bars.handle(event);
        }
    });

    tracing::info!("flashing ELF file: {}", cli.elf.display());
    let loader = flashing::build_loader(&mut session, &cli.elf, format, None)?;
    let vector_table_addr = loader
        .vector_table_addr()
        .with_context(|| "failed to determine vector table address from ELF")?;
    let flash_timer = Instant::now();
    loader.commit(&mut session, download_opts)?;
    tracing::info!(
        "flashing finished in {:.2}s",
        flash_timer.elapsed().as_secs_f32()
    );

    session.prepare_running_on_ram(vector_table_addr, 0)?;
    let mut core = session.core(0)?;

    // Open the serial console and start capturing from it now, before releasing either core:
    // the target can start UARTing out its boot log the instant `core.run()` returns, and both
    // that and `core1.run()` below are themselves slow JTAG round-trips, so opening the port
    // only after them would reliably lose the target's first output.
    let serial_reader = config
        .serial
        .as_ref()
        .map(open_serial_console)
        .transpose()?;

    tracing::info!("running core");
    core.run()?;
    drop(core);

    // On a JtagCascaded (dual Cortex-A9) target, CPU1 shows up as a separate debug core that
    // hw_server/the probe may halt on attach independently of CPU0. Our own boot code releases
    // CPU1 from the boot ROM's park loop via the mailbox+SEV protocol, but that has no effect if
    // CPU1 is sitting halted at the debug level, so make sure it's running too.
    let mut core1 = session.core(1)?;
    core1.run()?;

    if let Some(serial_reader) = serial_reader {
        run_serial_console(serial_reader)?;
    }

    Ok(())
}
