use std::{
    collections::HashMap,
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

use anyhow::Context;
use indicatif::{MultiProgress, ProgressBar, ProgressStyle};
use probe_rs::{
    Core, MemoryInterface, Permissions,
    architecture::arm::dp::DpAddress,
    flashing::{
        self, DownloadOptions, ElfLoader, ElfOptions, FlashProgress, ProgressEvent,
        ProgressOperation,
    },
    probe::{DebugProbeSelector, Probe, WireProtocol, list::Lister},
};
use tracing_subscriber::EnvFilter;
use z7_run_data::{PsInitOps, RegOp, RegOpKind};

/// Default chunk size for RAM writes during `commit()`, in bytes. Without chunking, each RAM
/// region is written to the target in one single call and progress jumps straight from 0% to
/// 100% - see [`ProgressBars`]. Overridable via `--ram-chunk-size`.
const DEFAULT_RAM_CHUNK_SIZE: u64 = 64 * 1024;

/// Default `openFPGALoader` board name, used when `OPENFPGALOADER_BOARD` isn't set.
const DEFAULT_OPENFPGALOADER_BOARD: &str = "zedboard";

/// Config file name looked up in the current directory when `--config` isn't given.
const DEFAULT_CONFIG_FILE_NAME: &str = "z7_run.toml";

/// Parses a `u64` from either decimal or `0x`/`0X`-prefixed hex, for CLI args like `--check-ddr`
/// where the natural way to write the value is as a hex address.
fn parse_maybe_hex_u64(s: &str) -> Result<u64, std::num::ParseIntError> {
    match s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        Some(hex) => u64::from_str_radix(hex, 16),
        None => s.parse(),
    }
}

/// Resolves a path that came from a config file: if it's relative, resolves it relative to the
/// config file's own directory rather than the current working directory, so a config file
/// referencing files next to it keeps working no matter where `z7-run` is invoked from.
fn resolve_relative_to_config(config_path: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        config_path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join(path)
    }
}

/// Z7 flasher application.
///
/// Unifies all the steps required to flash and run a Rust program on a Z7-based system,
/// including flashing a PL design. It uses the probe-rs library to talk to the debug probe.
///
/// - Connects to the probe.
/// - Resets the target.
/// - Executes the PS7 (PLL/clock/DDR) init sequence.
/// - Optionally flashes a bitstream to the programmable logic, by calling out to the external
///   `openFPGALoader` program.
/// - Flashes and runs the given ELF file.
#[derive(clap::Parser, Debug)]
#[command(version, about, verbatim_doc_comment)]
struct Cli {
    /// Path to the RON file containing the PS7 PLL/clock/DDR/DDRIOB register op sequences, as
    /// generated by `z7-ps7init-extract`. Overrides the `ZYNQ_REGS` env var when set.
    #[arg(long)]
    regs: Option<PathBuf>,

    /// Path to the ELF file to flash and run.
    elf: PathBuf,

    /// Check the DDR after init by writing/reading a few distinct bit patterns at the given test
    /// address (decimal or `0x`-prefixed hex, e.g. `0x00100000`).
    #[arg(long, value_parser = parse_maybe_hex_u64)]
    check_ddr: Option<u64>,

    /// Path to a config TOML file (bitstream/openFPGALoader setup, serial console). If not given,
    /// looks for `z7_run.toml` in the current directory; if that isn't found either, the
    /// bitstream step falls back to the `ZYNQ_BITSTREAM`/`OPENFPGALOADER_BOARD` env vars and the
    /// serial console step is skipped entirely.
    #[arg(long)]
    config: Option<PathBuf>,

    /// Debug probe to use, as `VID:PID[-INTERFACE][:SERIAL]` (same format as probe-rs itself,
    /// e.g. `0403:6010` or `0403:6010:ABCD1234`). If not given and multiple probes are
    /// connected, you'll be prompted to pick one interactively.
    #[arg(long)]
    probe: Option<DebugProbeSelector>,

    /// Chunk size, in bytes, for writing the ELF into RAM. Smaller chunks give more granular
    /// progress reporting at the cost of a bit of overhead. Defaults to
    /// [`DEFAULT_RAM_CHUNK_SIZE`]; passing this explicitly as the same value as the ELF size (or
    /// larger) writes each RAM region in one go, same as probe-rs's own `--ram-chunk-size` when
    /// left unset, so progress then jumps straight to 100%.
    #[arg(long)]
    ram_chunk_size: Option<u64>,

    /// Don't show a progress bar while flashing.
    #[arg(long)]
    no_progress: bool,

    /// JTAG clock speed in kHz. Overrides the config file's `jtag_speed_khz` when given. If
    /// neither is set, the probe's own default speed is used.
    #[arg(long)]
    jtag_speed_khz: Option<u32>,

    /// Read the ELF back off the target after flashing and compare it against what was written.
    /// Off by default, since verification takes roughly as long as the write itself.
    #[arg(long)]
    verify: bool,
}

/// Config for things that don't belong on the command line, split by what they actually
/// describe: `fpga` is genuinely board-specific (bitstream, openFPGALoader board name/args), but
/// `serial` mostly isn't - which serial port shows up depends on what's plugged into *this*
/// machine, not on the board - it just lives in the same file for convenience.
#[derive(Debug, Default, serde::Deserialize)]
struct Config {
    #[serde(default)]
    fpga: FpgaConfig,
    /// Serial console to attach to (printing anything received to stdout) once every init/flash
    /// step is done and the target is running.
    #[serde(default)]
    serial: Option<SerialConfig>,
    /// JTAG clock speed in kHz. Overridden by `--jtag-speed-khz` when given; if neither is set,
    /// the probe's own default speed is used.
    #[serde(default)]
    jtag_speed_khz: Option<u32>,
}

#[derive(Debug, Default, serde::Deserialize)]
struct FpgaConfig {
    /// Path to the bitstream to load via openFPGALoader before the ELF is flashed. Overridden by
    /// the `ZYNQ_BITSTREAM` env var when set, so a quick one-off override doesn't require editing
    /// the config file. Relative paths are resolved relative to the config file's own directory,
    /// not the current working directory, so the config stays self-contained wherever `z7-run`
    /// is invoked from.
    #[serde(default)]
    bitstream: Option<PathBuf>,
    /// Board name passed to openFPGALoader via `-b`. Overridden by the `OPENFPGALOADER_BOARD` env
    /// var when set; defaults to [`DEFAULT_OPENFPGALOADER_BOARD`] if neither is set.
    #[serde(default)]
    board: Option<String>,
    /// Extra arguments appended to the openFPGALoader invocation, after `-b <board> <bitstream>`
    /// (e.g. `["--freq", "10e6"]` or a cable selector).
    #[serde(default)]
    args: Vec<String>,
}

#[derive(Debug, serde::Deserialize)]
struct SerialConfig {
    /// Serial port device path (e.g. `/dev/ttyUSB1`).
    port: String,
    /// Baud rate. Defaults to 115200, the near-universal default for these boards' UARTs.
    #[serde(default = "default_baud_rate")]
    baud_rate: u32,
}

fn default_baud_rate() -> u32 {
    115_200
}

/// Picks which debug probe to open. With `selector` given, matches against it directly (same as
/// probe-rs's own `--probe`) and errors if that doesn't resolve to exactly one probe. Without a
/// selector: opens the only probe if there's just one, or prompts interactively to choose among
/// several - there's no correct default to silently pick when more than one probe is connected.
fn select_probe(lister: &Lister, selector: Option<&DebugProbeSelector>) -> anyhow::Result<Probe> {
    use std::io::Write as _;

    let probes = lister.list(selector);
    match probes.len() {
        0 => match selector {
            Some(selector) => anyhow::bail!("no debug probe found matching --probe {selector}"),
            None => anyhow::bail!("no debug probes found"),
        },
        1 => Ok(probes[0].open()?),
        _ => {
            if let Some(selector) = selector {
                anyhow::bail!(
                    "multiple debug probes match --probe {selector}; narrow it down further \
                     (e.g. add the interface or serial number)"
                );
            }
            println!("Multiple debug probes found:");
            for (i, probe) in probes.iter().enumerate() {
                println!("  [{i}] {probe}");
            }
            print!("Select a probe [0-{}]: ", probes.len() - 1);
            std::io::stdout().flush()?;
            let mut input = String::new();
            std::io::stdin()
                .read_line(&mut input)
                .with_context(|| "failed to read probe selection")?;
            let index: usize = input
                .trim()
                .parse()
                .with_context(|| format!("invalid probe selection: {:?}", input.trim()))?;
            let probe = probes
                .get(index)
                .ok_or_else(|| anyhow::anyhow!("selection {index} is out of range"))?;
            Ok(probe.open()?)
        }
    }
}

/// Renders [`ProgressEvent`]s emitted by [`flashing::FlashLoader::commit`] as live terminal
/// progress bars. probe-rs itself only ships this event stream (see `FlashProgress`) - the
/// library deliberately stays UI-agnostic since consumers render it differently (the probe-rs
/// CLI's own indicatif bars, the VS Code debug adapter, ...) - so there's no ready-made bar
/// widget to reuse here. z7-run only ever flashes into RAM (no on-chip flash algorithm is
/// involved), so in practice there's just one bar ("Writing RAM"); this stays generic over
/// [`ProgressOperation`] regardless, in case a target/ELF combination ever exercises the flash
/// erase/program/verify path too.
struct FlashProgressBars {
    multi_progress: MultiProgress,
    bars: HashMap<&'static str, ProgressBar>,
}

impl FlashProgressBars {
    fn new() -> Self {
        Self {
            multi_progress: MultiProgress::new(),
            bars: HashMap::new(),
        }
    }

    fn operation_label(operation: ProgressOperation) -> &'static str {
        match operation {
            ProgressOperation::Fill => "Reading flash",
            ProgressOperation::Erase => "Erasing",
            ProgressOperation::Program => "Programming",
            ProgressOperation::Verify => "Verifying",
            ProgressOperation::Ram => "Writing RAM",
        }
    }

    fn bar_mut(&mut self, operation: ProgressOperation) -> &mut ProgressBar {
        self.bars
            .entry(Self::operation_label(operation))
            .or_insert_with(ProgressBar::hidden)
    }

    fn handle(&mut self, event: ProgressEvent) {
        match event {
            ProgressEvent::FlashLayoutReady { .. } | ProgressEvent::Started(_) => {}
            ProgressEvent::AddProgressBar { operation, total } => {
                let bar = self.multi_progress.add(match total {
                    // A length is promised, but only known for sure once flashing starts; start
                    // at 1 so the bar doesn't render as already at 100%.
                    Some(total) => ProgressBar::new(total.max(1)),
                    None => ProgressBar::no_length(),
                });
                let template = if bar.length().is_some() {
                    "{msg:>13.green.bold} {spinner} {percent:>3}% [{bar:20}] {bytes:>10} @ {bytes_per_sec:>12} (ETA {eta})"
                } else {
                    "{msg:>13.green.bold} {spinner} {elapsed}"
                };
                bar.set_style(
                    ProgressStyle::with_template(template)
                        .expect("static progress bar template is valid")
                        .progress_chars("##-"),
                );
                bar.set_message(Self::operation_label(operation));
                bar.enable_steady_tick(Duration::from_millis(100));
                self.bars.insert(Self::operation_label(operation), bar);
            }
            ProgressEvent::Progress {
                operation, size, ..
            } => self.bar_mut(operation).inc(size),
            ProgressEvent::Failed(operation) => self.bar_mut(operation).abandon(),
            ProgressEvent::Finished(operation) => {
                let bar = self.bar_mut(operation);
                bar.set_length(bar.position());
                bar.finish();
            }
            ProgressEvent::DiagnosticMessage { message } => {
                let _ = self.multi_progress.println(message);
            }
        }
    }
}

/// Flashes the given bitstream with `openFPGALoader`, passing `-b <board>` as its own explicit
/// argument (rather than folding it into `extra_args`) plus whatever else `extra_args` carries.
///
/// Must be called with no probe-rs `Session`/`Probe` alive: `openFPGALoader` needs exclusive
/// access to the same USB JTAG interface, and will fail to open it while probe-rs is still
/// holding it (same reason `zynq7000-init.py` sleeps after xsct disconnects, before probe-rs
/// tries to open the same interface).
fn flash_bitstream(bitstream: &str, board: &str, extra_args: &[String]) -> anyhow::Result<()> {
    tracing::info!("flashing bitstream via openFPGALoader: {bitstream} (board: {board})");
    let status = std::process::Command::new("openFPGALoader")
        .args(["-b", board])
        .arg(bitstream)
        .args(extra_args)
        .status()
        .with_context(|| "failed to spawn openFPGALoader (is it on PATH?)")?;
    if !status.success() {
        anyhow::bail!("openFPGALoader exited with {status}");
    }
    Ok(())
}

/// Opens the configured serial port and prints anything received to stdout, forever. Meant to be
/// the last thing `main` does: once the target is up and running, this is how you watch its UART
/// output without needing a separate terminal/tool.
fn attach_serial_console(serial: &SerialConfig) -> anyhow::Result<()> {
    use std::io::{Read, Write};

    tracing::info!(
        "attaching to serial console: {} @ {} baud",
        serial.port,
        serial.baud_rate
    );
    let mut port = serialport::new(&serial.port, serial.baud_rate)
        .timeout(Duration::from_millis(100))
        .open()
        .with_context(|| format!("failed to open serial port {}", serial.port))?;

    let mut buf = [0u8; 1024];
    let mut stdout = std::io::stdout();
    loop {
        match port.read(&mut buf) {
            Ok(n) => {
                stdout.write_all(&buf[..n])?;
                stdout.flush()?;
            }
            Err(e) if e.kind() == std::io::ErrorKind::TimedOut => {}
            Err(e) => return Err(e).with_context(|| "failed to read from serial console"),
        }
    }
}

/// Writes a few distinct bit patterns to DDR and reads them back, to give an unambiguous
/// pass/fail signal for whether DDR is actually working, independent of whether an app flashed
/// afterward appears to run. A stuck-at fault or bit swap from bad calibration won't show up as
/// a probe-rs error during flashing (writing bytes and issuing `core.run()` can't detect a CPU
/// that immediately crashes on a garbage stack pointer), so this needs to be checked directly.
fn ddr_sanity_check(core: &mut Core, base_addr: u64) -> anyhow::Result<()> {
    let patterns: [u32; 4] = [0xDEAD_BEEF, 0x0000_0000, 0xFFFF_FFFF, 0xAAAA_5555];
    for (i, &pattern) in patterns.iter().enumerate() {
        core.write_word_32(base_addr + (i as u64) * 4, pattern)?;
    }
    for (i, &pattern) in patterns.iter().enumerate() {
        let addr = base_addr + (i as u64) * 4;
        let read_back = core.read_word_32(addr)?;
        if read_back != pattern {
            anyhow::bail!(
                "DDR sanity check failed at {addr:#010x}: wrote {pattern:#010x}, read back {read_back:#010x}"
            );
        }
    }
    Ok(())
}

/// Executes a sequence of register ops (as extracted from `ps7_init.tcl`) directly over the
/// core's memory interface (i.e. via JTAG), in order.
fn execute_register_ops(core: &mut Core, ops: &[RegOp]) -> anyhow::Result<()> {
    for op in ops {
        tracing::debug!(
            "performing register op: {} {:#010x}",
            op.name.as_deref().unwrap_or("<unnamed>"),
            op.addr()
        );
        match op.kind {
            RegOpKind::Write { addr, val } => core.write_word_32(addr as u64, val)?,
            RegOpKind::MaskWrite { addr, mask, val } => {
                let addr = addr as u64;
                let current = core.read_word_32(addr)?;
                core.write_word_32(addr, (current & !mask) | (val & mask))?;
            }
            RegOpKind::MaskPoll { addr, mask } => {
                let deadline = std::time::Instant::now() + Duration::from_secs(1);
                loop {
                    let current = core.read_word_32(addr as u64)?;
                    if current & mask != 0 {
                        break;
                    }
                    if std::time::Instant::now() > deadline {
                        anyhow::bail!(
                            "timed out waiting for register {addr:#010x} & {mask:#010x} != 0 (last read: {current:#010x})"
                        );
                    }
                }
            }
        }
    }
    Ok(())
}

fn main() -> anyhow::Result<()> {
    use clap::Parser as _;

    // Default to info for this app but warn-and-above for probe-rs, which is otherwise very
    // chatty at info level (JTAG scans, AP/DP setup, session teardown, ...). RUST_LOG still
    // overrides this entirely when set.
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("info,probe_rs=warn")),
        )
        .init();

    let cli = Cli::parse();

    // An explicit --config must exist (fail loud); an implicit default lookup is fine to come up
    // empty (just proceed without a config).
    let config_path: Option<PathBuf> = match &cli.config {
        Some(path) => Some(path.clone()),
        None => {
            let default_path = PathBuf::from(DEFAULT_CONFIG_FILE_NAME);
            default_path.exists().then_some(default_path)
        }
    };

    let config: Config = match &config_path {
        Some(path) => {
            tracing::info!("loading config from: {}", path.display());
            let config_str = std::fs::read_to_string(path)
                .with_context(|| format!("failed to read config file {}", path.display()))?;
            toml::from_str(&config_str)
                .with_context(|| format!("failed to parse config file {}", path.display()))?
        }
        None => {
            tracing::debug!(
                "no --config given and no {DEFAULT_CONFIG_FILE_NAME} in the current directory, \
                 proceeding without one"
            );
            Config::default()
        }
    };

    // `--regs` and `ZYNQ_REGS` are both plain CLI/env-relative paths, resolved relative to the
    // current working directory like any other CLI argument - no config-file involved, so no
    // `resolve_relative_to_config` needed here.
    let regs: PathBuf = cli
        .regs
        .clone()
        .or_else(|| std::env::var_os("ZYNQ_REGS").map(PathBuf::from))
        .ok_or_else(|| {
            anyhow::anyhow!(
                "no PS7 init ops RON file specified: pass --regs <path> or set ZYNQ_REGS"
            )
        })?;

    // A quick `ZYNQ_BITSTREAM=... z7-run ...`/`OPENFPGALOADER_BOARD=... z7-run ...` shouldn't
    // require editing the config file.
    let bitstream = std::env::var("ZYNQ_BITSTREAM").ok().or_else(|| {
        let bitstream = config.fpga.bitstream.as_ref()?;
        let resolved = match &config_path {
            Some(config_path) => resolve_relative_to_config(config_path, bitstream),
            None => bitstream.clone(),
        };
        Some(resolved.display().to_string())
    });
    let board = std::env::var("OPENFPGALOADER_BOARD")
        .ok()
        .or_else(|| config.fpga.board.clone())
        .unwrap_or_else(|| DEFAULT_OPENFPGALOADER_BOARD.to_string());

    tracing::info!("loading PS7 init ops from: {}", regs.display());
    let ron_str = std::fs::read_to_string(&regs)
        .with_context(|| format!("failed to read PS7 init ops file {}", regs.display()))?;
    let ps7_init_ops: PsInitOps = ron::from_str(&ron_str)
        .with_context(|| format!("failed to parse PS7 init ops file {}", regs.display()))?;

    let jtag_speed_khz = cli.jtag_speed_khz.or(config.jtag_speed_khz);

    let lister = Lister::new();
    let mut probe = select_probe(&lister, cli.probe.as_ref())?;
    probe.select_protocol(WireProtocol::Jtag)?;
    if let Some(jtag_speed_khz) = jtag_speed_khz {
        tracing::info!("setting JTAG speed to {jtag_speed_khz} kHz");
        probe.set_speed(jtag_speed_khz)?;
    }

    tracing::info!("attaching to target board");

    let mut session = probe.attach("X7Z", Permissions::default())?;
    let mut core = session.core(0)?;

    tracing::info!("resetting and halting core");
    core.reset_and_halt(Duration::from_millis(100))?;

    // Execution order mirrors the real ps7_init.tcl call order: DDRIOB config -> PLL init ->
    // clock init -> DDR init -> post-config. DDRIOB configures the
    // physical I/O buffers (drive strength/termination) for the DDR pins, so it has to be done
    // before the DDR controller starts its calibration handshake, or that handshake never
    // completes (status register stuck at 0, DDR_INIT_OPS mask_poll times out). Post-config
    // (level shifters + PL reset deassert) runs last, same as on real hardware where
    // `ps7_post_config` is called right after `ps7_init` regardless of whether/when a bitstream
    // gets loaded - the PL powers up in reset and stays there until this runs.
    tracing::info!("performing board clock and DDR init");
    execute_register_ops(&mut core, &ps7_init_ops.ddriob_init_ops)
        .with_context(|| "DDRIOB register setup")?;
    tracing::debug!("bringing up PLLs");
    execute_register_ops(&mut core, &ps7_init_ops.pll_init_ops)
        .with_context(|| "PLL register setup")?;
    tracing::debug!("configuring clocks");
    execute_register_ops(&mut core, &ps7_init_ops.clock_init_ops)
        .with_context(|| "Clock config setup")?;
    tracing::debug!("initializing DDR controller");
    execute_register_ops(&mut core, &ps7_init_ops.ddr_init_ops)
        .with_context(|| "DDR controller register setup")?;
    tracing::debug!("running PS7 post-config (level shifters, PL reset deassert)");
    execute_register_ops(&mut core, &ps7_init_ops.post_config_ops)
        .with_context(|| "PS7 post-config register setup")?;

    if let Some(test_addr) = cli.check_ddr {
        tracing::info!("running DDR sanity check at {test_addr:#010x}");
        ddr_sanity_check(&mut core, test_addr).with_context(|| "DDR sanity check")?;
        tracing::info!("DDR sanity check passed");
    }

    drop(core);

    // openFPGALoader needs exclusive access to the same USB JTAG interface probe-rs is holding
    // open, so fully release the probe/session before spawning it, then re-attach afterward.
    // Reprogramming the PL (FPGA fabric) doesn't touch the PS's DDR/PLL/SLCR state, so the init
    // done above survives the round trip - only the JTAG connection itself needs to be redone.
    // Skip the whole dance when there's nothing to flash, to avoid the extra latency/reset churn.
    if let Some(bitstream) = &bitstream {
        // `probe` was already consumed by `probe.attach()` above; dropping `session` alone
        // releases the underlying USB JTAG handle.
        drop(session);

        flash_bitstream(bitstream, &board, &config.fpga.args)?;

        tracing::info!("re-attaching probe after bitstream flash");
        let lister = Lister::new();
        let mut probe = select_probe(&lister, cli.probe.as_ref())?;
        probe.select_protocol(WireProtocol::Jtag)?;
        if let Some(jtag_speed_khz) = jtag_speed_khz {
            probe.set_speed(jtag_speed_khz)?;
        }
        session = probe.attach("X7Z", Permissions::default())?;
    }

    let arm_if = session.get_arm_interface()?;
    arm_if.select_debug_port(DpAddress::Default)?;

    let format = ElfLoader(ElfOptions::default());

    // Must outlive `download_opts`: its `progress` field borrows this closure-captured state, and
    // is used up to (and dropped as part of) `loader.commit()` below.
    let mut progress_bars = (!cli.no_progress).then(FlashProgressBars::new);

    let mut download_opts = DownloadOptions::default();
    download_opts.verify = cli.verify;
    // Without chunking, each RAM region is written to the target in one single call and progress
    // jumps straight from 0% to 100%.
    download_opts.ram_chunk_size = Some(cli.ram_chunk_size.unwrap_or(DEFAULT_RAM_CHUNK_SIZE));
    download_opts.progress = FlashProgress::new(|event| {
        if let Some(progress_bars) = &mut progress_bars {
            progress_bars.handle(event);
        }
    });

    tracing::info!("flashing ELF file: {}", cli.elf.display());
    let loader = flashing::build_loader(&mut session, &cli.elf, format, None)?;
    let vector_table_addr = loader
        .vector_table_addr()
        .with_context(|| "failed to determine vector table address from ELF")?;
    let flash_timer = Instant::now();
    loader.commit(&mut session, download_opts)?;
    tracing::info!(
        "flashing finished in {:.2}s",
        flash_timer.elapsed().as_secs_f32()
    );

    session.prepare_running_on_ram(vector_table_addr, 0)?;
    let mut core = session.core(0)?;

    tracing::info!("running core");
    core.run()?;

    if let Some(serial) = &config.serial {
        attach_serial_console(serial)?;
    }

    Ok(())
}
