# .gitlab-ci.yml

image: rust:latest

variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo_cache

stages:
  - stage1
  - stage2

.common_setup:
  before_script:
    - cargo install just
  cache:
    paths: 
      - '.cargo_cache/'
      - 'firmware/target/'
      - 'host/target/'
    key: cargo-cache

check:
  stage: stage1
  extends: .common_setup
  script:
    - just check-dir firmware
    - just check-dir host

build:
  stage: stage2
  extends: .common_setup
  script:
    - just build-zynq
    - just build-dir host

fmt:
  stage: stage1
  extends: .common_setup
  script:
    - just check-fmt-dir firmware
    - just check-fmt-dir host

docs:
  stage: stage1
  extends: .common_setup
  script:
    - rustup install nightly
    - rustup component add rust-src --toolchain nightly
    - rustup target add armv7a-none-eabihf --toolchain nightly
    - just docs-zynq

clippy:
  stage: stage1
  extends: .common_setup
  script:
    - just clippy-dir firmware
    - just clippy-dir host
