#![doc = r"This file was auto-generated by the [zynq7000-ps7init-extract](https://egit.irs.uni-stuttgart.de/rust/zynq7000-rs/src/branch/main/tools/zynq7000-ps7init-extract) program."]
#![doc = r""]
#![doc = r"This configuration file contains static DDRIOB configuration parameters extracted from the"]
#![doc = r"AMD ps7init.tcl file"]
use zynq7000::ddrc::regs;
use zynq7000_hal::ddr::DdriobConfigSet;
pub const DDRIOB_CONFIG_SET_ZEDBOARD: DdriobConfigSet = DdriobConfigSet {
    addr0: regs::DdriobConfig::new_with_raw_value(0x00000600),
    addr1: regs::DdriobConfig::new_with_raw_value(0x00000600),
    data0: regs::DdriobConfig::new_with_raw_value(0x00000672),
    data1: regs::DdriobConfig::new_with_raw_value(0x00000672),
    diff0: regs::DdriobConfig::new_with_raw_value(0x00000674),
    diff1: regs::DdriobConfig::new_with_raw_value(0x00000674),
    clock: regs::DdriobConfig::new_with_raw_value(0x00000600),
};
