//! # Rust peripheral acess crate to the AMD Zynq 7000 SoCs
//!
//! This crate provides a low-level register access API building on the
//! [`derive-mmio` crate](https://crates.io/crates/derive-mmio). However, its structure
//! is similar to the crates auto-generated by [`svd2rust`](https://docs.rs/svd2rust/latest/svd2rust/#peripheral-api).
//!
//! This crate is purposely kept low-level to allow building higher level abstractions like HALs
//! on top of it.
//! [The Zynq7000 HAL library](https://egit.irs.uni-stuttgart.de/rust/zynq7000-rs/src/branch/main/zynq7000-hal)
//! contains such a HAL which builds on this PAC.
#![no_std]

use core::sync::atomic::{AtomicBool, Ordering};

#[cfg(test)]
extern crate std;

pub const MPCORE_BASE_ADDR: usize = 0xF8F0_0000;

pub mod ddrc;
pub mod devcfg;
pub mod eth;
pub mod gic;
pub mod gpio;
pub mod gtc;
pub mod i2c;
pub mod l2_cache;
pub mod mpcore;
pub mod priv_tim;
pub mod qspi;
pub mod slcr;
pub mod spi;
pub mod ttc;
pub mod uart;
pub mod xadc;

static PERIPHERALS_TAKEN: AtomicBool = AtomicBool::new(false);

/// This is a collection of all the processing peripherals.
///
/// It is a singleton which exposes all peripherals supported by this crate.
/// The [`svd2rust` documentation](https://docs.rs/svd2rust/latest/svd2rust/#peripheral-api)
/// provides some more information about this.
pub struct Peripherals {
    pub gicc: gic::MmioGicCpuInterface<'static>,
    pub gicd: gic::MmioGicDistributor<'static>,
    pub l2c: l2_cache::MmioL2Cache<'static>,
    pub ddrc: ddrc::MmioDdrController<'static>,
    pub uart_0: uart::MmioUart<'static>,
    pub uart_1: uart::MmioUart<'static>,
    pub spi_0: spi::MmioSpi<'static>,
    pub spi_1: spi::MmioSpi<'static>,
    pub i2c_0: i2c::MmioI2c<'static>,
    pub i2c_1: i2c::MmioI2c<'static>,
    pub gtc: gtc::MmioGlobalTimerCounter<'static>,
    pub gpio: gpio::MmioGpio<'static>,
    pub slcr: slcr::MmioSlcr<'static>,
    pub ttc_0: ttc::MmioTtc<'static>,
    pub ttc_1: ttc::MmioTtc<'static>,
    pub eth_0: eth::MmioEthernet<'static>,
    pub eth_1: eth::MmioEthernet<'static>,
    pub qspi: qspi::MmioQspi<'static>,
    pub devcfg: devcfg::MmioDevCfg<'static>,
    pub xadc: xadc::MmioXAdc<'static>,
}

impl Peripherals {
    /// Returns all supported processing system peripherals *once*.
    pub fn take() -> Option<Self> {
        let taken = PERIPHERALS_TAKEN.swap(true, Ordering::Relaxed);
        if taken {
            return None;
        }
        Some(unsafe { Self::steal() })
    }

    /// Unchecked version of [Self::take].
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    pub unsafe fn steal() -> Self {
        unsafe {
            Self {
                gicc: gic::GicCpuInterface::new_mmio_fixed(),
                gicd: gic::GicDistributor::new_mmio_fixed(),
                l2c: l2_cache::L2Cache::new_mmio_fixed(),
                ddrc: ddrc::DdrController::new_mmio_fixed(),
                uart_0: uart::Uart::new_mmio_fixed_0(),
                uart_1: uart::Uart::new_mmio_fixed_1(),
                gtc: gtc::GlobalTimerCounter::new_mmio_fixed(),
                gpio: gpio::Gpio::new_mmio_fixed(),
                slcr: slcr::Slcr::new_mmio_fixed(),
                spi_0: spi::Spi::new_mmio_fixed_0(),
                spi_1: spi::Spi::new_mmio_fixed_1(),
                i2c_0: i2c::I2c::new_mmio_fixed_0(),
                i2c_1: i2c::I2c::new_mmio_fixed_1(),
                ttc_0: ttc::Ttc::new_mmio_fixed_0(),
                ttc_1: ttc::Ttc::new_mmio_fixed_1(),
                eth_0: eth::Ethernet::new_mmio_fixed_0(),
                eth_1: eth::Ethernet::new_mmio_fixed_1(),
                qspi: qspi::Qspi::new_mmio_fixed(),
                devcfg: devcfg::DevCfg::new_mmio_fixed(),
                xadc: xadc::XAdc::new_mmio_fixed(),
            }
        }
    }
}

#[bitbybit::bitenum(u1, exhaustive = true)]
#[derive(Debug, PartialEq, Eq)]
pub enum SpiClockPhase {
    ActiveOutsideOfWord = 0,
    InactiveOutsideOfWord = 1,
}

#[bitbybit::bitenum(u1, exhaustive = true)]
#[derive(Debug, PartialEq, Eq)]
pub enum SpiClockPolarity {
    QuiescentLow = 0,
    QuiescentHigh = 1,
}
