use std::fs::File;
use std::io::Write;
use std::process::Command;
//use zynq7000_rt::mmu::ONE_MB;
//pub use zynq7000_rt::mmu::segments::*;

pub const MAX_DDR_SIZE: usize = 0x4000_0000;
pub const ONE_MB: usize = 0x10_0000;

pub mod offsets {
    pub const OFFSET_DDR: usize = 0;
    pub const OFFSET_DDR_ALL_ACCESSIBLE: usize = 0x10_0000;

    pub const OFFSET_FPGA_SLAVE_0: usize = 0x4000_0000;
    pub const OFFSET_FPGA_SLAVE_1_START: usize = 0x8000_0000;
    pub const OFFSET_FPGA_SLAVE_1_END: usize = 0xC000_0000;

    pub const OFFSET_IO_PERIPHERALS_START: usize = 0xE000_0000;
    pub const OFFSET_IO_PERIPHERALS_END: usize = 0xE030_0000;

    pub const OFFSET_NAND_MEMORY: usize = 0xE100_0000;
    pub const OFFSET_NOR_MEMORY: usize = 0xE200_0000;
    pub const OFFSET_SRAM_MEMORY: usize = 0xE400_0000;
    pub const OFFSET_SMC_MEMORIES_END: usize = 0xE600_0000;

    /// 0xf8000c00 to 0xf8000fff, 0xf8010000 to 0xf88fffff and
    /// 0xf8f03000 to 0xf8ffffff are reserved  but due to granual size of
    /// 1MB, it is not possible to define separate regions for them.
    pub const OFFSET_AMBA_APB_START: usize = 0xF800_0000;
    pub const OFFSET_AMBA_APB_END: usize = 0xF900_0000;

    pub const OFFSET_QSPI_XIP_START: usize = 0xFC00_0000;
    pub const OFFSET_QSPI_XIP_END: usize = 0xFE00_0000;

    /// 0xfff00000 to 0xfffb0000 is reserved but due to granual size of
    /// 1MB, it is not possible to define separate region for it
    pub const OFFSET_OCM_MAPPED_HIGH_START: usize = 0xFFF0_0000;
    pub const OFFSET_OCM_MAPPED_HIGH_END: u64 = 0x1_0000_0000;
}

pub mod segments {
    pub use super::offsets::*;
    use super::{MAX_DDR_SIZE, ONE_MB};

    /// First 1 MB of DDR has special treatment, access is dependant on SCU/OCM state.
    /// Refer to Zynq TRM UG585 p.106 for more details.
    pub const DDR_FULL_ACCESSIBLE: usize = (MAX_DDR_SIZE - ONE_MB) / ONE_MB;
    pub const FPGA_SLAVE: usize = (OFFSET_FPGA_SLAVE_1_START - OFFSET_FPGA_SLAVE_0) / ONE_MB;
    pub const UNASSIGNED_0: usize =
        (OFFSET_IO_PERIPHERALS_START - OFFSET_FPGA_SLAVE_1_END) / ONE_MB;
    pub const IO_PERIPHS: usize =
        (OFFSET_IO_PERIPHERALS_END - OFFSET_IO_PERIPHERALS_START) / ONE_MB;
    pub const UNASSIGNED_1: usize = (OFFSET_NAND_MEMORY - OFFSET_IO_PERIPHERALS_END) / ONE_MB;
    pub const NAND: usize = (OFFSET_NOR_MEMORY - OFFSET_NAND_MEMORY) / ONE_MB;
    pub const NOR: usize = (OFFSET_SRAM_MEMORY - OFFSET_NOR_MEMORY) / ONE_MB;
    pub const SRAM: usize = (OFFSET_SMC_MEMORIES_END - OFFSET_SRAM_MEMORY) / ONE_MB;
    pub const SEGMENTS_UNASSIGNED_2: usize =
        (OFFSET_AMBA_APB_START - OFFSET_SMC_MEMORIES_END) / ONE_MB;
    pub const AMBA_APB: usize = (OFFSET_AMBA_APB_END - OFFSET_AMBA_APB_START) / ONE_MB;
    pub const UNASSIGNED_3: usize = (OFFSET_QSPI_XIP_START - OFFSET_AMBA_APB_END) / ONE_MB;
    pub const QSPI_XIP: usize = (OFFSET_QSPI_XIP_END - OFFSET_QSPI_XIP_START) / ONE_MB;
    pub const UNASSIGNED_4: usize = (OFFSET_OCM_MAPPED_HIGH_START - OFFSET_QSPI_XIP_END) / ONE_MB;
    pub const OCM_MAPPED_HIGH: usize = ((OFFSET_OCM_MAPPED_HIGH_END
        - OFFSET_OCM_MAPPED_HIGH_START as u64)
        / ONE_MB as u64) as usize;
}

use segments::*;

macro_rules! write_l1_section {
    ($writer:expr, $offset:expr, $attr:expr) => {
        writeln!(
            $writer,
            "L1Section::new_with_addr_and_attrs({:#010x}, {}),",
            $offset, $attr
        )
        .unwrap();
    };
}

fn main() {
    let file_path = "mmu_table.rs";
    let file = File::create(file_path).expect("Failed to create file");

    let mut offset = 0;
    let attr_ddr = stringify!(section_attrs::DDR);
    let attr_unassigned = stringify!(section_attrs::UNASSIGNED_RESERVED);
    let attr_fpga_slaves = stringify!(section_attrs::FPGA_SLAVES);
    let attr_shared_dev = stringify!(section_attrs::SHAREABLE_DEVICE);
    let attr_sram = stringify!(section_attrs::SRAM);
    let attr_qspi = stringify!(section_attrs::QSPI_XIP);
    let attr_ocm_high = stringify!(section_attrs::OCM_MAPPED_HIGH);

    assert_eq!(
        1 + DDR_FULL_ACCESSIBLE
            + FPGA_SLAVE
            + FPGA_SLAVE
            + UNASSIGNED_0
            + IO_PERIPHS
            + UNASSIGNED_1
            + NAND
            + NOR
            + SRAM
            + SEGMENTS_UNASSIGNED_2
            + AMBA_APB
            + UNASSIGNED_3
            + QSPI_XIP
            + UNASSIGNED_4
            + OCM_MAPPED_HIGH,
        4096
    );

    let mut buf_writer = std::io::BufWriter::new(file);
    writeln!(
        buf_writer,
        "//! This file was auto-generated by table-gen.rs"
    )
    .unwrap();

    writeln!(buf_writer, "use crate::mmu::section_attrs;").unwrap();
    writeln!(buf_writer, "use cortex_ar::mmu::L1Section;").unwrap();
    writeln!(buf_writer, "use zynq7000_mmu::L1Table;").unwrap();
    writeln!(buf_writer).unwrap();

    writeln!(buf_writer, "/// MMU Level 1 Page table.").unwrap();
    writeln!(buf_writer, "///").unwrap();
    writeln!(
        buf_writer,
        "/// 4096 entries, each covering 1MB of the address space."
    )
    .unwrap();
    writeln!(
        buf_writer,
        "pub static MMU_L1_PAGE_TABLE: L1Table = L1Table::new(["
    )
    .unwrap();

    writeln!(
        buf_writer,
        "// First DDR segment, OCM memory (0x0000_0000 - 0x0010_0000)"
    )
    .unwrap();
    write_l1_section!(buf_writer, offset, attr_ddr);

    offset += ONE_MB;
    writeln!(buf_writer, "// DDR memory (0x00100000 - 0x4000_0000)").unwrap();
    for _ in 0..DDR_FULL_ACCESSIBLE {
        write_l1_section!(buf_writer, offset, attr_ddr);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// FPGA slave 0 (0x4000_0000 - 0x8000_0000)").unwrap();
    for _ in 0..FPGA_SLAVE {
        write_l1_section!(buf_writer, offset, attr_fpga_slaves);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// FPGA slave 1 (0x8000_0000 - 0xC000_0000)").unwrap();
    for _ in 0..FPGA_SLAVE {
        write_l1_section!(buf_writer, offset, attr_fpga_slaves);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// Unassigned/Reserved (0xC000_0000 - 0xE000_0000)"
    )
    .unwrap();
    for _ in 0..UNASSIGNED_0 {
        write_l1_section!(buf_writer, offset, attr_unassigned);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// Segments IO peripherals (0xE000_0000 - 0xE030_0000)"
    )
    .unwrap();
    for _ in 0..IO_PERIPHS {
        write_l1_section!(buf_writer, offset, attr_shared_dev);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// Unassigned/Reserved (0xE030_0000 - 0xE100_0000)"
    )
    .unwrap();
    for _ in 0..UNASSIGNED_1 {
        write_l1_section!(buf_writer, offset, attr_unassigned);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// NAND (0xE100_0000 - 0xE200_0000)").unwrap();
    for _ in 0..NAND {
        write_l1_section!(buf_writer, offset, attr_shared_dev);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// NOR (0xE200_0000 - 0xE400_0000)").unwrap();
    for _ in 0..NOR {
        write_l1_section!(buf_writer, offset, attr_shared_dev);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// SRAM (0xE400_0000 - 0xE600_0000)").unwrap();
    for _ in 0..SRAM {
        write_l1_section!(buf_writer, offset, attr_sram);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// Unassigned/Reserved (0xE600_0000 - 0xF800_0000)"
    )
    .unwrap();
    for _ in 0..SEGMENTS_UNASSIGNED_2 {
        write_l1_section!(buf_writer, offset, attr_unassigned);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// AMBA APB peripherals (0xF800_0000 - 0xF900_0000)"
    )
    .unwrap();
    for _ in 0..AMBA_APB {
        write_l1_section!(buf_writer, offset, attr_shared_dev);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// Unassigned/Reserved (0xF900_0000 - 0xFC00_0000)"
    )
    .unwrap();
    for _ in 0..UNASSIGNED_3 {
        write_l1_section!(buf_writer, offset, attr_unassigned);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// QSPI XIP (0xFC00_0000 - 0xFE00_0000)").unwrap();
    for _ in 0..QSPI_XIP {
        write_l1_section!(buf_writer, offset, attr_qspi);
        offset += ONE_MB;
    }

    writeln!(
        buf_writer,
        "// Unassiged/Reserved (0xFE00_0000 - 0xFFF0_0000)"
    )
    .unwrap();
    for _ in 0..UNASSIGNED_4 {
        write_l1_section!(buf_writer, offset, attr_unassigned);
        offset += ONE_MB;
    }

    writeln!(buf_writer, "// OCM High (0xFFF0_0000 - 0xFFFF_FFFF)").unwrap();
    let mut offset_u64 = offset as u64;
    for _ in 0..OCM_MAPPED_HIGH {
        write_l1_section!(buf_writer, offset, attr_ocm_high);

        offset_u64 += ONE_MB as u64;
    }
    // Check that the full 4 GB were covered (not too much, or less)
    assert_eq!(offset_u64, 0x1_0000_0000_u64);

    writeln!(buf_writer, "]);").unwrap();
    // Finish the file.
    drop(buf_writer);
    println!("Generated mmu_table.rs");

    // Run rustfmt on the generated file
    let output = Command::new("rustfmt")
        .arg(file_path)
        .output()
        .expect("Failed to run rustfmt");

    if !output.status.success() {
        eprintln!("rustfmt failed: {:?}", output);
    }
}
