//! # Rust peripheral acess crate to the AMD Zynq 7000 SoCs
//!
//! This crate provides a low-level register access API building on the
//! [`derive-mmio` crate](https://crates.io/crates/derive-mmio). However, its structure
//! is similar to the crates auto-generated by [`svd2rust`](https://docs.rs/svd2rust/latest/svd2rust/#peripheral-api).
//!
//! This crate is purposely kept low-level to allow building higher level abstractions like HALs
//! on top of it.
//! [The Zynq7000 HAL library](https://github.com/us-irs/zynq7000-rs/tree/main/zynq/zynq7000-hal)
//! contains such a HAL which builds on this PAC.
//!
//! ## Features
//!
//! * `defmt` - Add support for the [`defmt`](https://github.com/knurling-rs/defmt) logging library.
#![no_std]
#![deny(missing_docs)]
#![cfg_attr(docsrs, feature(doc_cfg))]

use core::sync::atomic::{AtomicBool, Ordering};

#[cfg(test)]
extern crate std;

/// Base address of the MPCore private memory region.
pub const MPCORE_BASE_ADDR: usize = 0xF8F0_0000;

pub mod axi;
/// DDR memory controller.
pub mod ddrc;
/// Device configuration interface.
pub mod devcfg;
pub mod eth;
pub mod gic;
pub mod gpio;
pub mod gtc;
pub mod i2c;
/// PL310 L2 cache controller.
pub mod l2_cache;
pub mod mpcore;
pub mod priv_tim;
/// Quad-SPI controller.
pub mod qspi;
/// SD/SDIO controller.
pub mod sdio;
pub mod slcr;
pub mod spi;
pub mod swdt;
pub mod ttc;
pub mod uart;
pub mod usb;
/// XADC analog-to-digital converter.
pub mod xadc;

static PERIPHERALS_TAKEN: AtomicBool = AtomicBool::new(false);

/// This is a collection of processing system peripherals.
///
/// It is a singleton which exposes peripherals supported by this crate.
/// The [`svd2rust` documentation](https://docs.rs/svd2rust/latest/svd2rust/#peripheral-api)
/// provides some more information about this.
pub struct Peripherals {
    /// GIC CPU interface.
    pub gicc: gic::MmioCpuInterfaceRegisters<'static>,
    /// GIC distributor.
    pub gicd: gic::MmioDistributorRegisters<'static>,
    /// L2 cache controller.
    pub l2c: l2_cache::MmioRegisters<'static>,
    /// DDR memory controller.
    pub ddrc: ddrc::MmioRegisters<'static>,
    /// UART controller 0.
    pub uart_0: uart::MmioRegisters<'static>,
    /// UART controller 1.
    pub uart_1: uart::MmioRegisters<'static>,
    /// SPI controller 0.
    pub spi_0: spi::MmioRegisters<'static>,
    /// SPI controller 1.
    pub spi_1: spi::MmioRegisters<'static>,
    /// I2C controller 0.
    pub i2c_0: i2c::MmioRegisters<'static>,
    /// I2C controller 1.
    pub i2c_1: i2c::MmioRegisters<'static>,
    /// Global timer counter.
    pub gtc: gtc::MmioRegisters<'static>,
    /// GPIO controller.
    pub gpio: gpio::MmioRegisters<'static>,
    /// System level control registers.
    pub slcr: slcr::MmioRegisters<'static>,
    /// Triple timer counter 0.
    pub ttc_0: ttc::MmioRegisters<'static>,
    /// Triple timer counter 1.
    pub ttc_1: ttc::MmioRegisters<'static>,
    /// Gigabit Ethernet controller 0.
    pub eth_0: eth::MmioRegisters<'static>,
    /// Gigabit Ethernet controller 1.
    pub eth_1: eth::MmioRegisters<'static>,
    /// Quad-SPI controller.
    pub qspi: qspi::MmioRegisters<'static>,
    /// Device configuration interface.
    pub devcfg: devcfg::MmioRegisters<'static>,
    /// XADC analog-to-digital converter.
    pub xadc: xadc::MmioRegisters<'static>,
    /// SD/SDIO controller 0.
    pub sdio_0: sdio::MmioRegisters<'static>,
    /// SD/SDIO controller 1.
    pub sdio_1: sdio::MmioRegisters<'static>,
    /// System Watchdog Timer.
    pub swdt: swdt::MmioRegisters<'static>,
}

impl Peripherals {
    /// Returns all supported processing system peripherals *once*.
    pub fn take() -> Option<Self> {
        let taken = PERIPHERALS_TAKEN.swap(true, Ordering::Relaxed);
        if taken {
            return None;
        }
        Some(unsafe { Self::steal() })
    }

    /// Unchecked version of [Self::take].
    ///
    /// # Safety
    ///
    /// Each of the returned peripherals must be used at most once.
    pub unsafe fn steal() -> Self {
        unsafe {
            Self {
                gicc: gic::CpuInterfaceRegisters::new_mmio_fixed(),
                gicd: gic::DistributorRegisters::new_mmio_fixed(),
                l2c: l2_cache::Registers::new_mmio_fixed(),
                ddrc: ddrc::Registers::new_mmio_fixed(),
                uart_0: uart::Registers::new_mmio_fixed_0(),
                uart_1: uart::Registers::new_mmio_fixed_1(),
                gtc: gtc::Registers::new_mmio_fixed(),
                gpio: gpio::Registers::new_mmio_fixed(),
                slcr: slcr::Registers::new_mmio_fixed(),
                spi_0: spi::Registers::new_mmio_fixed_0(),
                spi_1: spi::Registers::new_mmio_fixed_1(),
                i2c_0: i2c::Registers::new_mmio_fixed_0(),
                i2c_1: i2c::Registers::new_mmio_fixed_1(),
                ttc_0: ttc::Registers::new_mmio_fixed_0(),
                ttc_1: ttc::Registers::new_mmio_fixed_1(),
                eth_0: eth::Registers::new_mmio_fixed_0(),
                eth_1: eth::Registers::new_mmio_fixed_1(),
                qspi: qspi::Registers::new_mmio_fixed(),
                devcfg: devcfg::Registers::new_mmio_fixed(),
                xadc: xadc::Registers::new_mmio_fixed(),
                sdio_0: sdio::Registers::new_mmio_fixed_0(),
                sdio_1: sdio::Registers::new_mmio_fixed_1(),
                swdt: swdt::Registers::new_mmio_fixed(),
            }
        }
    }
}

/// SPI clock phase, controlling when data is driven relative to the SPI clock edges.
#[bitbybit::bitenum(u1, exhaustive = true)]
#[derive(Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum SpiClockPhase {
    /// Clock is active outside the word.
    ActiveOutsideOfWord = 0,
    /// Clock is inactive outside the word.
    InactiveOutsideOfWord = 1,
}

/// SPI clock polarity, the quiescent state of the SPI clock line.
#[bitbybit::bitenum(u1, exhaustive = true)]
#[derive(Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum SpiClockPolarity {
    /// Clock is low when quiescent.
    QuiescentLow = 0,
    /// Clock is high when quiescent.
    QuiescentHigh = 1,
}
