[package]
name = "zynq7000-rt"
version = "0.4.0"
edition = "2024"
description = "Basic startup and run-time support for the Zynq7000 family of SoCs"
homepage = "https://github.com/us-irs/zynq7000-rs"
repository = "https://github.com/us-irs/zynq7000-rs"
license = "MIT OR Apache-2.0"
keywords = ["no-std", "rt", "cortex-a", "amd", "zynq7000"]
categories = ["embedded", "no-std", "hardware-support"]

[dependencies]
aarch32-rt = { version = "0.4", optional = true, features = ["fpu-d32"] }
aarch32-cpu = { version = "0.4" }
arbitrary-int = "2"
zynq7000 = { path = "../zynq7000", version = "0.6" }

[build-dependencies]
arm-targets = { version = "0.4" }

[features]
default = ["rt"]
rt = ["dep:aarch32-rt"]

[package.metadata.docs.rs]
targets = ["armv7a-none-eabihf"]
rustdoc-args = ["--generate-link-to-definition"]
